// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQO2BmNaZcast3fRMTUUo7FzvuupdTE0w',
    appId: '1:1072971256470:web:1fd0e2d50054f48a9328b7',
    messagingSenderId: '1072971256470',
    projectId: 'compact-mystery-420806',
    authDomain: 'compact-mystery-420806.firebaseapp.com',
    storageBucket: 'compact-mystery-420806.appspot.com',
    measurementId: 'G-5MDD2BR4PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAVboQDzl_XQ_DEVDITaWqq61OVlHJgXc',
    appId: '1:1072971256470:android:00ab654923080c979328b7',
    messagingSenderId: '1072971256470',
    projectId: 'compact-mystery-420806',
    storageBucket: 'compact-mystery-420806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2arHB3842FgRno3ur6dq8CBEPiIhVh2Q',
    appId: '1:1072971256470:ios:69857c3ee8d3c9319328b7',
    messagingSenderId: '1072971256470',
    projectId: 'compact-mystery-420806',
    storageBucket: 'compact-mystery-420806.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2arHB3842FgRno3ur6dq8CBEPiIhVh2Q',
    appId: '1:1072971256470:ios:69857c3ee8d3c9319328b7',
    messagingSenderId: '1072971256470',
    projectId: 'compact-mystery-420806',
    storageBucket: 'compact-mystery-420806.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrudApp',
  );
}
